Product:
  type: object
  config:
    resolveField: '@=resolver("App\\GraphQL\\Resolver\\ProductResolver", [info, value, args])'
    fields:
      id:
        type: Int
      name:
        type: String